# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_hoteles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='titulo',
            field=models.CharField(blank=True, default='default', max_length=50, null=True),
        ),
    ]
